#!/bin/bash
#
# Merges two files of property settings together and returns them integrated in a single .xml configuration file.
# First argument is the cluster properties file, second argument the node specific properties file.

CLUSTER_PROPS=$1
NODE_PROPS=$2

BEGINNING="<?xml version=\"1.0\"?>\n<?xml-stylesheet type=\"text/xsl\" href=\"configuration.xsl\"?>\n<configuration>\n<!-- ### AUTOGENERATED - DO NOT EDIT DIRECTLY ### -->"
ENDING="</configuration>"

echo -e $BEGINNING
echo -e "<!-- NODE PROPERTIES START -->"
echo "$(cat $NODE_PROPS)"
echo -e "<!-- NODE PROPERTIES END -->"
echo -e "<!-- CLUSTER PROPERTIES START -->"
echo "$(cat $CLUSTER_PROPS)"
echo -e "<!-- CLUSTER PROPERTIES END -->"
echo -e $ENDING
