#!/bin/bash
#
# Merges two files of configuration settings together and returns them integrated in a single .sh configuration file.
# First argument is the cluster configuration file, second argument the node specific configuration file.

CLUSTER_CONF=$1
NODE_CONF=$2

BEGINNING="### AUTOGENERATED - DO NOT EDIT DIRECTLY ###"

echo -e $BEGINNING
echo -e "### CLUSTER CONFIGURATION START (caution: may be overridden by node properties) ###"
echo "$(cat $CLUSTER_CONF)"
echo -e "### CLUSTER CONFIGURATION END ###"
echo -e "### NODE CONFIGURATION START ###"
echo "$(cat $NODE_CONF)"
echo -e "### NODE CONFIGURATION END ###"
